
# k8s/apps-deploy-svc.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-a
  template:
    metadata:
      labels:
        app: app-a
    spec:
      containers:
      - name: app-a
        image: vamsikpdevops/app-a:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-a-svc
spec:
  type: NodePort
  selector:
    app: app-a
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: app-b
        image: vamsikpdevops/app-b:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: app-b-svc
spec:
  type: NodePort
  selector:
    app: app-b
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30081
